apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dockgen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-dockgen
  template:
    metadata:
      labels:
        app: node-dockgen
    spec:
      containers:
      - name: node-dockgen
        image: alexmbarbosa/node-dockgen:$BUILD_NUMBER
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: node-dockgen-service
spec:
  selector:
    app: node-dockgen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
